#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Alzabo
version:      0.71
version_from: lib/Alzabo.pm
installdirs:  site
requires:
    Class::Factory::Util:          1.3
    Test::Harness:                 1.26
    Exception::Class:              0.97
    Params::Validate:              0.24
    Tie::IxHash:                   0
    Pod::Man:                      1.14
    Storable:                      0.7
    Test::Simple:                  0.44
    Time::HiRes:                   0
    DBI:                           1.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_01
