=pod

=head1 NAME

Alzabo and PostgreSQL

=head1 DESCRIPTION

This documentation is about what special support Alzabo has for PostgreSQL,
as well as what is lacking.

Postgres support is based on the 7.3.x version of Postgres.  Alzabo
should work with the 7.1 and 7.2 series, and may even work with the
7.0 series.

=head2 Reverse Engineering

=over 4

=item *

Alzabo cannot determine from the existence of a sequence that the
sequence is meant to be used for a particular column unless the
sequence was created as a result of making a column's type SERIAL.

This is because there is no link between the two in the Postgres' data
dictionary tables and will probably never change.

=back

=head2 Transactions

=over 4

=item *

Transactions are fully supported with Postgres.

=back

=head2 Outer joins

=over 4

=item *

Left and right outer joins are supported.

=item *

Full outer joins are not supported.

=back

=cut
